from app.apps.saas.models import SandboxCopyJob, SandboxEnvironment
from phase10_test_utils import auth_headers


def test_sandbox_request_and_refresh_are_metadata_safe(client, db):
    headers = auth_headers(client, db, permissions=["sandbox_view", "sandbox_manage"])
    create = client.post("/api/v1/admin/sandbox/create", json={"name": "UAT", "copy_sample_data": False}, headers=headers)
    assert create.status_code == 201, create.text
    sandbox_id = create.json()["id"]
    assert "generated by deployment infrastructure" in create.json()["access_url_placeholder"].lower()
    assert db.query(SandboxCopyJob).first().detail_json["production_writes_blocked"] is True

    refresh = client.post(f"/api/v1/admin/sandbox/{sandbox_id}/refresh", headers=headers)
    assert refresh.status_code == 201
    assert db.query(SandboxEnvironment).first().status == "refresh_queued"
