import { api } from "@/services/api";
import type { SRMRecord } from "./types";

export const srmApi = {
  moduleInfo: () => api.get("/srm/module-info").then((res) => res.data),
  dashboard: () => api.get("/srm/dashboard").then((res) => res.data),
  customer360: (params?: Record<string, string | number | undefined>) => api.get("/srm/customer-360", { params }).then((res) => res.data),
  salesOrders: () => api.get<SRMRecord[]>("/srm/sales-orders").then((res) => res.data),
  salesOrder: (id: number) => api.get<SRMRecord>(`/srm/sales-orders/${id}`).then((res) => res.data),
  createSalesOrder: (data: SRMRecord) => api.post("/srm/sales-orders", data).then((res) => res.data),
  updateSalesOrder: (id: number, data: SRMRecord) => api.patch(`/srm/sales-orders/${id}`, data).then((res) => res.data),
  addSalesOrderLine: (id: number, data: SRMRecord) => api.post(`/srm/sales-orders/${id}/lines`, data).then((res) => res.data),
  updateSalesOrderLine: (id: number, lineId: number, data: SRMRecord) => api.patch(`/srm/sales-orders/${id}/lines/${lineId}`, data).then((res) => res.data),
  deleteSalesOrderLine: (id: number, lineId: number) => api.delete(`/srm/sales-orders/${id}/lines/${lineId}`).then((res) => res.data),
  contracts: () => api.get<SRMRecord[]>("/srm/contracts").then((res) => res.data),
  contract: (id: number) => api.get<SRMRecord>(`/srm/contracts/${id}`).then((res) => res.data),
  createContract: (data: SRMRecord) => api.post("/srm/contracts", data).then((res) => res.data),
  updateContract: (id: number, data: SRMRecord) => api.patch(`/srm/contracts/${id}`, data).then((res) => res.data),
  engagements: () => api.get<SRMRecord[]>("/srm/engagements").then((res) => res.data),
  engagement: (id: number) => api.get<SRMRecord>(`/srm/engagements/${id}`).then((res) => res.data),
  createEngagement: (data: SRMRecord) => api.post("/srm/engagements", data).then((res) => res.data),
  updateEngagement: (id: number, data: SRMRecord) => api.patch(`/srm/engagements/${id}`, data).then((res) => res.data),
  updateEngagementStatus: (id: number, status: string) => api.post(`/srm/engagements/${id}/status/${status}`).then((res) => res.data),
  billingPlans: () => api.get<SRMRecord[]>("/srm/billing-plans").then((res) => res.data),
  billingPlan: (id: number) => api.get<SRMRecord>(`/srm/billing-plans/${id}`).then((res) => res.data),
  createBillingPlan: (data: SRMRecord) => api.post("/srm/billing-plans", data).then((res) => res.data),
  updateBillingPlan: (id: number, data: SRMRecord) => api.patch(`/srm/billing-plans/${id}`, data).then((res) => res.data),
  addBillingMilestone: (id: number, data: SRMRecord) => api.post(`/srm/billing-plans/${id}/milestones`, data).then((res) => res.data),
  invoiceDrafts: () => api.get<SRMRecord[]>("/srm/invoice-drafts").then((res) => res.data),
  invoices: () => api.get<SRMRecord[]>("/srm/invoices").then((res) => res.data),
  invoice: (id: number) => api.get<SRMRecord>(`/srm/invoices/${id}`).then((res) => res.data),
  addInvoiceLine: (id: number, data: SRMRecord) => api.post(`/srm/invoices/${id}/lines`, data).then((res) => res.data),
  manualInvoice: (data: SRMRecord) => api.post("/srm/invoices/manual", data).then((res) => res.data),
  draftInvoiceFromEngagement: (id: number) => api.post(`/srm/invoices/draft-from-engagement/${id}`).then((res) => res.data),
  draftInvoiceFromPmsMilestone: (id: number) => api.post(`/srm/invoices/draft-from-pms-milestone/${id}`).then((res) => res.data),
  draftInvoiceFromTimesheets: (data: SRMRecord) => api.post("/srm/invoices/draft-from-timesheets", data).then((res) => res.data),
  collectionsAging: () => api.get<SRMRecord[]>("/srm/collections/aging").then((res) => res.data),
  customerCollections: (customerId: number) => api.get(`/srm/collections/customer/${customerId}`).then((res) => res.data),
  createReceipt: (data: SRMRecord) => api.post("/srm/receipts", data).then((res) => res.data),
  confirmReceipt: (id: number) => api.post(`/srm/receipts/${id}/confirm`).then((res) => res.data),
  allocateReceipt: (id: number, data: SRMRecord) => api.post(`/srm/receipts/${id}/allocate`, data).then((res) => res.data),
  sendCollectionReminder: (data: SRMRecord) => api.post("/srm/collections/reminders/send", data).then((res) => res.data),
  escalateCollection: (invoiceId: number, data?: SRMRecord) => api.post(`/srm/collections/${invoiceId}/escalate`, data || {}).then((res) => res.data),
  requestWriteOff: (invoiceId: number, data?: SRMRecord) => api.post(`/srm/collections/${invoiceId}/write-off-request`, data || {}).then((res) => res.data),
  profitability: () => api.get<SRMRecord[]>("/srm/profitability").then((res) => res.data),
  profitabilityByFilters: (params?: Record<string, string | number | undefined>) => api.get("/srm/profitability", { params }).then((res) => res.data),
  leadToCash: () => api.get("/srm/reports/lead-to-cash").then((res) => res.data),
  reports: () => api.get("/srm/reports").then((res) => res.data),
  settings: () => api.get<SRMRecord[]>("/srm/settings").then((res) => res.data),
  updateSetting: (key: string, value_json: SRMRecord) => api.put(`/srm/settings/${key}`, { value_json }).then((res) => res.data),
  createSalesOrderFromCrmDeal: (dealId: number) => api.post(`/srm/from-crm/deals/${dealId}/create-sales-order`).then((res) => res.data),
  byCrmDeal: (dealId: number) => api.get(`/srm/by-crm-deal/${dealId}`).then((res) => res.data),
  engagementLifecycle: (id: number) => api.get(`/srm/engagements/${id}/lifecycle`).then((res) => res.data),
  submitSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/submit`).then((res) => res.data),
  approveSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/approve`).then((res) => res.data),
  confirmSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/confirm`).then((res) => res.data),
  cancelSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/cancel`).then((res) => res.data),
  closeSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/close`).then((res) => res.data),
  activateContract: (id: number) => api.post(`/srm/contracts/${id}/activate`).then((res) => res.data),
  expireContract: (id: number) => api.post(`/srm/contracts/${id}/expire`).then((res) => res.data),
  terminateContract: (id: number) => api.post(`/srm/contracts/${id}/terminate`).then((res) => res.data),
  renewContract: (id: number) => api.post(`/srm/contracts/${id}/renew`).then((res) => res.data),
  activateBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/activate`).then((res) => res.data),
  pauseBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/pause`).then((res) => res.data),
  completeBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/complete`).then((res) => res.data),
  cancelBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/cancel`).then((res) => res.data),
  createBillingPlanFromSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/billing-plan`).then((res) => res.data),
  draftInvoiceFromBillingMilestone: (id: number) => api.post(`/srm/invoices/draft-from-billing-milestone/${id}`).then((res) => res.data),
  draftInvoiceFromSalesOrder: (id: number) => api.post(`/srm/invoices/draft-from-sales-order/${id}`).then((res) => res.data),
  approveInvoice: (id: number) => api.post(`/srm/invoices/${id}/approve`).then((res) => res.data),
  sendInvoice: (id: number) => api.post(`/srm/invoices/${id}/send`).then((res) => res.data),
  createPmsProject: (id: number) => api.post(`/srm/engagements/${id}/create-pms-project`).then((res) => res.data),
  posSessions: () => api.get<SRMRecord[]>("/srm/pos/sessions").then((res) => res.data),
  activePosSession: () => api.get<SRMRecord>("/srm/pos/sessions/active").then((res) => res.data),
  openPosSession: (data: SRMRecord) => api.post("/srm/pos/sessions", data).then((res) => res.data),
  createPosCashMovement: (data: SRMRecord) => api.post("/srm/pos/cash-movements", data).then((res) => res.data),
  closePosSession: (data: SRMRecord) => api.post("/srm/pos/cashier-closing", data).then((res) => res.data),
  posHeldBills: () => api.get("/srm/pos/held-bills").then((res) => res.data),
  createPosHeldBill: (data: SRMRecord) => api.post("/srm/pos/held-bills", data).then((res) => res.data),
  recallPosHeldBill: (id: number | string) => api.post(`/srm/pos/held-bills/${id}/recall`).then((res) => res.data),
  deletePosHeldBill: (id: number | string) => api.delete(`/srm/pos/held-bills/${id}`).then((res) => res.data),
  posReturns: () => api.get("/srm/pos/returns").then((res) => res.data),
  createPosReturn: (data: SRMRecord) => api.post("/srm/pos/returns", data).then((res) => res.data),
  posReturn: (id: number | string) => api.get(`/srm/pos/returns/${id}`).then((res) => res.data),
  inventoryCategories: () => api.get("/srm/inventory/categories").then((res) => res.data),
  createInventoryCategory: (data: SRMRecord) => api.post("/srm/inventory/categories", data).then((res) => res.data),
  inventoryWarehouses: () => api.get("/srm/inventory/warehouses").then((res) => res.data),
  createInventoryWarehouse: (data: SRMRecord) => api.post("/srm/inventory/warehouses", data).then((res) => res.data),
  inventoryItems: (search?: string) => api.get(search ? `/srm/inventory/items?search=${encodeURIComponent(search)}` : "/srm/inventory/items").then((res) => res.data),
  createInventoryItem: (data: SRMRecord) => api.post("/srm/inventory/items", data).then((res) => res.data),
  inventoryItem: (id: number | string) => api.get(`/srm/inventory/items/${id}`).then((res) => res.data),
  updateInventoryItem: (id: number | string, data: SRMRecord) => api.put(`/srm/inventory/items/${id}`, data).then((res) => res.data),
  createInventoryOpeningStock: (data: SRMRecord) => api.post("/srm/inventory/opening-stock", data).then((res) => res.data),
  createInventoryStockMovement: (data: SRMRecord) => api.post("/srm/inventory/stock-movements", data).then((res) => res.data),
  createInventoryStockTransfer: (data: SRMRecord) => api.post("/srm/inventory/stock-transfers", data).then((res) => res.data),
  createInventoryStockAdjustment: (data: SRMRecord) => api.post("/srm/inventory/stock-adjustments", data).then((res) => res.data),
  purchaseOrders: () => api.get("/srm/procurement/purchase-orders").then((res) => res.data),
  createPurchaseOrder: (data: SRMRecord) => api.post("/srm/procurement/purchase-orders", data).then((res) => res.data),
  purchaseOrder: (id: number | string) => api.get(`/srm/procurement/purchase-orders/${id}`).then((res) => res.data),
  goodsReceipts: () => api.get("/srm/procurement/grn").then((res) => res.data),
  createGoodsReceipt: (data: SRMRecord) => api.post("/srm/procurement/grn", data).then((res) => res.data),
  goodsReceipt: (id: number | string) => api.get(`/srm/procurement/grn/${id}`).then((res) => res.data),
  priceLists: () => api.get("/srm/pricing/price-lists").then((res) => res.data),
  createPriceList: (data: SRMRecord) => api.post("/srm/pricing/price-lists", data).then((res) => res.data),
  priceList: (id: number | string) => api.get(`/srm/pricing/price-lists/${id}`).then((res) => res.data),
  lookupPrices: (data: SRMRecord) => api.post("/srm/pricing/lookup", data).then((res) => res.data),
  inventoryBatches: () => api.get("/srm/inventory/batches").then((res) => res.data),
  createInventoryBatch: (data: SRMRecord) => api.post("/srm/inventory/batches", data).then((res) => res.data),
  inventoryBatch: (id: number | string) => api.get(`/srm/inventory/batches/${id}`).then((res) => res.data),
  serialNumbers: () => api.get("/srm/inventory/serial-numbers").then((res) => res.data),
  createSerialNumber: (data: SRMRecord) => api.post("/srm/inventory/serial-numbers", data).then((res) => res.data),
  boms: () => api.get("/srm/inventory/manufacturing/bom").then((res) => res.data),
  createBom: (data: SRMRecord) => api.post("/srm/inventory/manufacturing/bom", data).then((res) => res.data),
  bom: (id: number | string) => api.get(`/srm/inventory/manufacturing/bom/${id}`).then((res) => res.data),
  productionOrders: () => api.get("/srm/inventory/manufacturing/orders").then((res) => res.data),
  createProductionOrder: (data: SRMRecord) => api.post("/srm/inventory/manufacturing/orders", data).then((res) => res.data),
  postProductionOrder: (id: number | string, data: SRMRecord) => api.post(`/srm/inventory/manufacturing/orders/${id}/post`, data).then((res) => res.data),
};
