import { api } from "@/services/api";
import type { SRMRecord } from "./types";

export const srmApi = {
  moduleInfo: () => api.get("/srm/module-info").then((res) => res.data),
  dashboard: () => api.get("/srm/dashboard").then((res) => res.data),
  customer360: (params?: Record<string, string | number | undefined>) => api.get("/srm/customer-360", { params }).then((res) => res.data),
  salesOrders: () => api.get<SRMRecord[]>("/srm/sales-orders").then((res) => res.data),
  salesOrder: (id: number) => api.get<SRMRecord>(`/srm/sales-orders/${id}`).then((res) => res.data),
  createSalesOrder: (data: SRMRecord) => api.post("/srm/sales-orders", data).then((res) => res.data),
  updateSalesOrder: (id: number, data: SRMRecord) => api.patch(`/srm/sales-orders/${id}`, data).then((res) => res.data),
  addSalesOrderLine: (id: number, data: SRMRecord) => api.post(`/srm/sales-orders/${id}/lines`, data).then((res) => res.data),
  updateSalesOrderLine: (id: number, lineId: number, data: SRMRecord) => api.patch(`/srm/sales-orders/${id}/lines/${lineId}`, data).then((res) => res.data),
  deleteSalesOrderLine: (id: number, lineId: number) => api.delete(`/srm/sales-orders/${id}/lines/${lineId}`).then((res) => res.data),
  contracts: () => api.get<SRMRecord[]>("/srm/contracts").then((res) => res.data),
  contract: (id: number) => api.get<SRMRecord>(`/srm/contracts/${id}`).then((res) => res.data),
  createContract: (data: SRMRecord) => api.post("/srm/contracts", data).then((res) => res.data),
  updateContract: (id: number, data: SRMRecord) => api.patch(`/srm/contracts/${id}`, data).then((res) => res.data),
  engagements: () => api.get<SRMRecord[]>("/srm/engagements").then((res) => res.data),
  engagement: (id: number) => api.get<SRMRecord>(`/srm/engagements/${id}`).then((res) => res.data),
  createEngagement: (data: SRMRecord) => api.post("/srm/engagements", data).then((res) => res.data),
  updateEngagement: (id: number, data: SRMRecord) => api.patch(`/srm/engagements/${id}`, data).then((res) => res.data),
  updateEngagementStatus: (id: number, status: string) => api.post(`/srm/engagements/${id}/status/${status}`).then((res) => res.data),
  billingPlans: () => api.get<SRMRecord[]>("/srm/billing-plans").then((res) => res.data),
  billingPlan: (id: number) => api.get<SRMRecord>(`/srm/billing-plans/${id}`).then((res) => res.data),
  createBillingPlan: (data: SRMRecord) => api.post("/srm/billing-plans", data).then((res) => res.data),
  updateBillingPlan: (id: number, data: SRMRecord) => api.patch(`/srm/billing-plans/${id}`, data).then((res) => res.data),
  addBillingMilestone: (id: number, data: SRMRecord) => api.post(`/srm/billing-plans/${id}/milestones`, data).then((res) => res.data),
  invoiceDrafts: () => api.get<SRMRecord[]>("/srm/invoice-drafts").then((res) => res.data),
  invoices: () => api.get<SRMRecord[]>("/srm/invoices").then((res) => res.data),
  invoice: (id: number) => api.get<SRMRecord>(`/srm/invoices/${id}`).then((res) => res.data),
  addInvoiceLine: (id: number, data: SRMRecord) => api.post(`/srm/invoices/${id}/lines`, data).then((res) => res.data),
  manualInvoice: (data: SRMRecord) => api.post("/srm/invoices/manual", data).then((res) => res.data),
  draftInvoiceFromEngagement: (id: number) => api.post(`/srm/invoices/draft-from-engagement/${id}`).then((res) => res.data),
  draftInvoiceFromPmsMilestone: (id: number) => api.post(`/srm/invoices/draft-from-pms-milestone/${id}`).then((res) => res.data),
  draftInvoiceFromTimesheets: (data: SRMRecord) => api.post("/srm/invoices/draft-from-timesheets", data).then((res) => res.data),
  collectionsAging: () => api.get<SRMRecord[]>("/srm/collections/aging").then((res) => res.data),
  customerCollections: (customerId: number) => api.get(`/srm/collections/customer/${customerId}`).then((res) => res.data),
  createReceipt: (data: SRMRecord) => api.post("/srm/receipts", data).then((res) => res.data),
  confirmReceipt: (id: number) => api.post(`/srm/receipts/${id}/confirm`).then((res) => res.data),
  allocateReceipt: (id: number, data: SRMRecord) => api.post(`/srm/receipts/${id}/allocate`, data).then((res) => res.data),
  sendCollectionReminder: (data: SRMRecord) => api.post("/srm/collections/reminders/send", data).then((res) => res.data),
  escalateCollection: (invoiceId: number, data?: SRMRecord) => api.post(`/srm/collections/${invoiceId}/escalate`, data || {}).then((res) => res.data),
  requestWriteOff: (invoiceId: number, data?: SRMRecord) => api.post(`/srm/collections/${invoiceId}/write-off-request`, data || {}).then((res) => res.data),
  profitability: () => api.get<SRMRecord[]>("/srm/profitability").then((res) => res.data),
  profitabilityByFilters: (params?: Record<string, string | number | undefined>) => api.get("/srm/profitability", { params }).then((res) => res.data),
  leadToCash: () => api.get("/srm/reports/lead-to-cash").then((res) => res.data),
  reports: () => api.get("/srm/reports").then((res) => res.data),
  settings: () => api.get<SRMRecord[]>("/srm/settings").then((res) => res.data),
  updateSetting: (key: string, value_json: SRMRecord) => api.put(`/srm/settings/${key}`, { value_json }).then((res) => res.data),
  createSalesOrderFromCrmDeal: (dealId: number) => api.post(`/srm/from-crm/deals/${dealId}/create-sales-order`).then((res) => res.data),
  byCrmDeal: (dealId: number) => api.get(`/srm/by-crm-deal/${dealId}`).then((res) => res.data),
  engagementLifecycle: (id: number) => api.get(`/srm/engagements/${id}/lifecycle`).then((res) => res.data),
  submitSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/submit`).then((res) => res.data),
  approveSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/approve`).then((res) => res.data),
  confirmSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/confirm`).then((res) => res.data),
  cancelSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/cancel`).then((res) => res.data),
  closeSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/close`).then((res) => res.data),
  activateContract: (id: number) => api.post(`/srm/contracts/${id}/activate`).then((res) => res.data),
  expireContract: (id: number) => api.post(`/srm/contracts/${id}/expire`).then((res) => res.data),
  terminateContract: (id: number) => api.post(`/srm/contracts/${id}/terminate`).then((res) => res.data),
  renewContract: (id: number) => api.post(`/srm/contracts/${id}/renew`).then((res) => res.data),
  activateBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/activate`).then((res) => res.data),
  pauseBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/pause`).then((res) => res.data),
  completeBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/complete`).then((res) => res.data),
  cancelBillingPlan: (id: number) => api.post(`/srm/billing-plans/${id}/cancel`).then((res) => res.data),
  createBillingPlanFromSalesOrder: (id: number) => api.post(`/srm/sales-orders/${id}/billing-plan`).then((res) => res.data),
  draftInvoiceFromBillingMilestone: (id: number) => api.post(`/srm/invoices/draft-from-billing-milestone/${id}`).then((res) => res.data),
  draftInvoiceFromSalesOrder: (id: number) => api.post(`/srm/invoices/draft-from-sales-order/${id}`).then((res) => res.data),
  approveInvoice: (id: number) => api.post(`/srm/invoices/${id}/approve`).then((res) => res.data),
  sendInvoice: (id: number) => api.post(`/srm/invoices/${id}/send`).then((res) => res.data),
  createPmsProject: (id: number) => api.post(`/srm/engagements/${id}/create-pms-project`).then((res) => res.data),
};
