import { test, expect } from "../frontend/node_modules/playwright/test";
import { authenticatePhase10 } from "./phase10-test-utils";

test("admin sandbox request and refresh render production-safe placeholder", async ({ page }) => {
  await authenticatePhase10(page);
  await page.goto("/admin/sandbox", { waitUntil: "domcontentloaded" });
  await page.getByRole("button", { name: "Create sandbox request" }).click();
  await expect(page.getByText("Generated by deployment infrastructure")).toBeVisible();
  await page.getByRole("button", { name: "Refresh" }).first().click();
  await expect(page.getByText("UAT Sandbox").first()).toBeVisible();
});
