from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from app.apps.ai_copilot.models import AIProviderSetting


@dataclass
class AIProviderResult:
    content: str
    confidence: float
    reasons: list[str]
    output: dict[str, Any]
    output_token_estimate: int


class AIProviderNotConfigured(Exception):
    pass


class AIProviderAdapter:
    def generate(self, *, use_case: str, prompt: str, context: dict[str, Any], setting: AIProviderSetting) -> AIProviderResult:
        raise NotImplementedError


class MockAIProviderAdapter(AIProviderAdapter):
    """Deterministic test adapter. It is only selected from explicit provider settings."""

    def generate(self, *, use_case: str, prompt: str, context: dict[str, Any], setting: AIProviderSetting) -> AIProviderResult:
        record_label = context.get("label") or f"{context.get('record_type') or 'record'} #{context.get('record_id') or '-'}"
        facts = context.get("fields") or {}
        fact_text = ", ".join(f"{key}: {value}" for key, value in list(facts.items())[:6]) or "No accessible fields"
        content = f"Mock AI {use_case.replace('_', ' ')} for {record_label}. Source evidence: {fact_text}."
        output = {
            "summary": content,
            "recommendations": [
                {
                    "text": f"Review next step for {record_label}",
                    "confidence": 0.82,
                    "reasons": ["Accessible record context was available", "Mock provider is enabled for tests"],
                }
            ],
            "score": 78 if use_case == "lead_score" else 64,
            "probability": 0.68,
            "confidence": 0.82,
            "reasons": ["Generated by configured mock provider", "Uses sanitized context only"],
            "source_summary": context.get("source_summary") or facts,
        }
        if use_case == "email_draft":
            output["draft"] = {
                "subject": f"Following up: {record_label}",
                "body": f"Hello,\n\n{content}\n\nPlease review before sending.",
                "requires_review": True,
            }
        if use_case == "workflow_draft":
            output["workflow_json"] = {
                "name": "AI drafted workflow",
                "active": False,
                "trigger": "manual_review_required",
                "steps": [{"type": "task", "label": "Review draft before activation"}],
            }
        return AIProviderResult(
            content=content,
            confidence=0.82,
            reasons=output["reasons"],
            output=output,
            output_token_estimate=max(1, len(str(output)) // 4),
        )


class ExternalProviderAdapter(AIProviderAdapter):
    def generate(self, *, use_case: str, prompt: str, context: dict[str, Any], setting: AIProviderSetting) -> AIProviderResult:
        raise AIProviderNotConfigured(
            f"{setting.provider_name} adapter is registered but no production connector is configured in this deployment."
        )


def adapter_for(setting: AIProviderSetting) -> AIProviderAdapter:
    provider = (setting.provider_name or "").strip().lower()
    if provider == "mock":
        return MockAIProviderAdapter()
    return ExternalProviderAdapter()

