import { api } from "@/services/api";
import type { FAMRecord } from "./types";

const list = (url: string) => api.get(url).then((res) => res.data);
const create = (url: string, data: FAMRecord) => api.post(url, data).then((res) => res.data);

export const famApi = {
  moduleInfo: () => api.get("/fam/module-info").then((res) => res.data),
  dashboard: () => api.get("/fam/dashboard").then((res) => res.data),
  settings: () => api.get("/fam/settings").then((res) => res.data),
  updateSettings: (data: FAMRecord) => api.put("/fam/settings", data).then((res) => res.data),
  financialYears: () => list("/fam/financial-years"),
  createFinancialYear: (data: FAMRecord) => create("/fam/financial-years", data),
  updateFinancialYear: (id: number, data: FAMRecord) => api.put(`/fam/financial-years/${id}`, data).then((res) => res.data),
  closeFinancialYear: (id: number) => api.post(`/fam/financial-years/${id}/close`).then((res) => res.data),
  lockFinancialYear: (id: number) => api.post(`/fam/financial-years/${id}/lock`).then((res) => res.data),
  chartOfAccounts: () => api.get("/fam/chart-of-accounts").then((res) => res.data),
  ledgerGroups: () => list("/fam/ledger-groups"),
  createLedgerGroup: (data: FAMRecord) => create("/fam/ledger-groups", data),
  updateLedgerGroup: (id: number, data: FAMRecord) => api.put(`/fam/ledger-groups/${id}`, data).then((res) => res.data),
  deleteLedgerGroup: (id: number) => api.delete(`/fam/ledger-groups/${id}`).then((res) => res.data),
  ledgers: () => list("/fam/ledgers"),
  createLedger: (data: FAMRecord) => create("/fam/ledgers", data),
  updateLedger: (id: number, data: FAMRecord) => api.put(`/fam/ledgers/${id}`, data).then((res) => res.data),
  deleteLedger: (id: number) => api.delete(`/fam/ledgers/${id}`).then((res) => res.data),
  openingBalances: () => list("/fam/opening-balances"),
  createOpeningBalance: (data: FAMRecord) => create("/fam/opening-balances", data),
  postOpeningBalances: () => api.post("/fam/opening-balances/post").then((res) => res.data),
  voucherTypes: () => list("/fam/voucher-types"),
  createVoucherType: (data: FAMRecord) => create("/fam/voucher-types", data),
  updateVoucherType: (id: number, data: FAMRecord) => api.put(`/fam/voucher-types/${id}`, data).then((res) => res.data),
  vouchers: () => list("/fam/vouchers"),
  createVoucher: (data: FAMRecord) => create("/fam/vouchers", data),
  getVoucher: (id: number | string) => api.get(`/fam/vouchers/${id}`).then((res) => res.data),
  updateVoucher: (id: number | string, data: FAMRecord) => api.put(`/fam/vouchers/${id}`, data).then((res) => res.data),
  postVoucher: (id: number | string) => api.post(`/fam/vouchers/${id}/post`).then((res) => res.data),
  cancelVoucher: (id: number | string, reason = "Cancelled from UI") => api.post(`/fam/vouchers/${id}/cancel`, { reason }).then((res) => res.data),
  reverseVoucher: (id: number | string) => api.post(`/fam/vouchers/${id}/reverse`).then((res) => res.data),
  cloneVoucher: (id: number | string, data: FAMRecord = {}) => api.post(`/fam/vouchers/${id}/clone`, data).then((res) => res.data),
  ledgerEntries: () => list("/fam/ledger-entries"),
  ledgerEntriesForLedger: (id: number | string) => api.get(`/fam/ledgers/${id}/entries`).then((res) => res.data),
  dayBook: () => list("/fam/day-book"),
  voucherAudit: (id: number | string) => list(`/fam/voucher-audit/${id}`),
  parties: (partyType?: string) => list(partyType ? `/fam/parties?party_type=${partyType}` : "/fam/parties"),
  createParty: (data: FAMRecord) => create("/fam/parties", data),
  getParty: (id: number | string) => api.get(`/fam/parties/${id}`).then((res) => res.data),
  updateParty: (id: number | string, data: FAMRecord) => api.put(`/fam/parties/${id}`, data).then((res) => res.data),
  createPartyLedger: (id: number | string) => api.post(`/fam/parties/${id}/create-ledger`).then((res) => res.data),
  partyStatement: (id: number | string) => list(`/fam/parties/${id}/statement`),
  partyOutstanding: (id: number | string) => api.get(`/fam/parties/${id}/outstanding`).then((res) => res.data),
  partyBillReferences: (id: number | string) => list(`/fam/parties/${id}/bill-references`),
  arAging: () => api.get("/fam/ar/aging").then((res) => res.data),
  apAging: () => api.get("/fam/ap/aging").then((res) => res.data),
  arOutstanding: () => api.get("/fam/ar/outstanding").then((res) => res.data),
  apOutstanding: () => api.get("/fam/ap/outstanding").then((res) => res.data),
  billReferences: () => list("/fam/bill-references"),
  createBillReference: (data: FAMRecord) => create("/fam/bill-references", data),
  billAllocations: () => list("/fam/bill-allocations"),
  createBillAllocation: (data: FAMRecord) => create("/fam/bill-allocations", data),
  partyCreditTerms: () => list("/fam/party-credit-terms"),
  createPartyCreditTerm: (data: FAMRecord) => create("/fam/party-credit-terms", data),
  srmIntegrationStatus: () => api.get("/fam/integrations/srm/status").then((res) => res.data),
  postSrmInvoice: (id: number | string) => api.post(`/fam/integrations/srm/post-invoice/${id}`).then((res) => res.data),
  postSrmReceipt: (id: number | string) => api.post(`/fam/integrations/srm/post-receipt/${id}`).then((res) => res.data),
  postSrmAllocation: (id: number | string) => api.post(`/fam/integrations/srm/post-allocation/${id}`).then((res) => res.data),
  reverseSrmPosting: (type: string, id: number | string) => api.post(`/fam/integrations/srm/reverse/${type}/${id}`).then((res) => res.data),
  postingJobs: () => list("/fam/posting-jobs"),
  postingJob: (id: number | string) => api.get(`/fam/posting-jobs/${id}`).then((res) => res.data),
  retryPostingJob: (id: number | string) => api.post(`/fam/posting-jobs/${id}/retry`).then((res) => res.data),
  postingRules: () => list("/fam/posting-rules"),
  createPostingRule: (data: FAMRecord) => create("/fam/posting-rules", data),
  updatePostingRule: (id: number | string, data: FAMRecord) => api.put(`/fam/posting-rules/${id}`, data).then((res) => res.data),
  bankAccounts: () => list("/fam/bank-accounts"),
  createBankAccount: (data: FAMRecord) => create("/fam/bank-accounts", data),
  updateBankAccount: (id: number | string, data: FAMRecord) => api.put(`/fam/bank-accounts/${id}`, data).then((res) => res.data),
  paymentModes: () => list("/fam/payment-modes"),
  createPaymentMode: (data: FAMRecord) => create("/fam/payment-modes", data),
  bankBook: () => api.get("/fam/bank-book").then((res) => res.data),
  cashBook: () => api.get("/fam/cash-book").then((res) => res.data),
  importBankStatement: (data: FAMRecord) => create("/fam/bank-statements/import", data),
  bankStatements: () => list("/fam/bank-statements"),
  bankStatement: (id: number | string) => api.get(`/fam/bank-statements/${id}`).then((res) => res.data),
  autoMatchBankStatement: (id: number | string) => api.post(`/fam/bank-statements/${id}/auto-match`).then((res) => res.data),
  matchBankStatement: (id: number | string, data: FAMRecord) => api.post(`/fam/bank-statements/${id}/match`, data).then((res) => res.data),
  ignoreBankStatementLine: (id: number | string, data: FAMRecord) => api.post(`/fam/bank-statements/${id}/ignore-line`, data).then((res) => res.data),
  reconcileBankStatement: (id: number | string) => api.post(`/fam/bank-statements/${id}/reconcile`).then((res) => res.data),
  bankReconciliation: () => api.get("/fam/bank-reconciliation").then((res) => res.data),
  postBankCharges: (data: FAMRecord) => create("/fam/bank-charges/post", data),
  postContra: (data: FAMRecord) => create("/fam/contra/post", data),
  gstRegistrations: () => list("/fam/gst/registrations"),
  createGstRegistration: (data: FAMRecord) => create("/fam/gst/registrations", data),
  gstRates: () => list("/fam/gst/rates"),
  createGstRate: (data: FAMRecord) => create("/fam/gst/rates", data),
  hsnSac: () => list("/fam/gst/hsn-sac"),
  createHsnSac: (data: FAMRecord) => create("/fam/gst/hsn-sac", data),
  calculateGst: (data: FAMRecord) => create("/fam/gst/calculate", data),
  gstSalesRegister: () => api.get("/fam/gst/sales-register").then((res) => res.data),
  gstPurchaseRegister: () => api.get("/fam/gst/purchase-register").then((res) => res.data),
  gstr1: () => api.get("/fam/gst/gstr1").then((res) => res.data),
  prepareGstr1: (data: FAMRecord) => create("/fam/gst/gstr1/prepare", data),
  gstr3b: () => api.get("/fam/gst/gstr3b").then((res) => res.data),
  prepareGstr3b: (data: FAMRecord) => create("/fam/gst/gstr3b/prepare", data),
  gstReconciliation: () => api.get("/fam/gst/reconciliation").then((res) => res.data),
  einvoiceSettings: () => api.get("/fam/gst/einvoice-settings").then((res) => res.data),
  updateEinvoiceSettings: (data: FAMRecord) => api.put("/fam/gst/einvoice-settings", data).then((res) => res.data),
  generateEinvoice: (id: number | string) => api.post(`/fam/gst/einvoice/generate/${id}`).then((res) => res.data),
  cancelEinvoice: (id: number | string) => api.post(`/fam/gst/einvoice/cancel/${id}`).then((res) => res.data),
  ewaybillSettings: () => api.get("/fam/gst/ewaybill-settings").then((res) => res.data),
  updateEwaybillSettings: (data: FAMRecord) => api.put("/fam/gst/ewaybill-settings", data).then((res) => res.data),
  generateEwaybill: (id: number | string) => api.post(`/fam/gst/ewaybill/generate/${id}`).then((res) => res.data),
  cancelEwaybill: (id: number | string) => api.post(`/fam/gst/ewaybill/cancel/${id}`).then((res) => res.data),
  purchaseBills: () => list("/fam/purchase-bills"),
  createPurchaseBill: (data: FAMRecord) => create("/fam/purchase-bills", data),
  purchaseBill: (id: number | string) => api.get(`/fam/purchase-bills/${id}`).then((res) => res.data),
  updatePurchaseBill: (id: number | string, data: FAMRecord) => api.put(`/fam/purchase-bills/${id}`, data).then((res) => res.data),
  postPurchaseBill: (id: number | string) => api.post(`/fam/purchase-bills/${id}/post`).then((res) => res.data),
  cancelPurchaseBill: (id: number | string) => api.post(`/fam/purchase-bills/${id}/cancel`).then((res) => res.data),
  expenses: () => list("/fam/expenses"),
  createExpense: (data: FAMRecord) => create("/fam/expenses", data),
  postExpense: (id: number | string) => api.post(`/fam/expenses/${id}/post`).then((res) => res.data),
  tdsSections: () => list("/fam/tds/sections"),
  createTdsSection: (data: FAMRecord) => create("/fam/tds/sections", data),
  tdsRates: () => list("/fam/tds/rates"),
  createTdsRate: (data: FAMRecord) => create("/fam/tds/rates", data),
  calculateTds: (data: FAMRecord) => create("/fam/tds/calculate", data),
  tdsTransactions: () => list("/fam/tds/transactions"),
  tdsPayable: () => api.get("/fam/tds/payable").then((res) => res.data),
  purchaseRegister: () => api.get("/fam/purchase-register").then((res) => res.data),
  expenseRegister: () => api.get("/fam/expense-register").then((res) => res.data),
  payablesDashboard: () => api.get("/fam/payables/dashboard").then((res) => res.data),
  prepareVendorPayment: (data: FAMRecord) => create("/fam/vendor-payments/prepare", data),
  postVendorPayment: (data: FAMRecord) => create("/fam/vendor-payments/post", data),
  inventoryDashboard: () => api.get("/fam/inventory/dashboard").then((res) => res.data),
  inventorySourceAudit: () => api.get("/fam/inventory/source-audit").then((res) => res.data),
  inventoryItems: (search?: string) => list(search ? `/fam/inventory/items?search=${encodeURIComponent(search)}` : "/fam/inventory/items"),
  createInventoryItem: (data: FAMRecord) => create("/fam/inventory/items", data),
  inventoryItem: (id: number | string) => api.get(`/fam/inventory/items/${id}`).then((res) => res.data),
  updateInventoryItem: (id: number | string, data: FAMRecord) => api.put(`/fam/inventory/items/${id}`, data).then((res) => res.data),
  inventoryStockGroups: () => list("/fam/inventory/stock-groups"),
  createInventoryStockGroup: (data: FAMRecord) => create("/fam/inventory/stock-groups", data),
  inventoryUnits: () => list("/fam/inventory/units"),
  createInventoryUnit: (data: FAMRecord) => create("/fam/inventory/units", data),
  inventoryWarehouses: () => list("/fam/inventory/warehouses"),
  createInventoryWarehouse: (data: FAMRecord) => create("/fam/inventory/warehouses", data),
  createInventoryOpeningStock: (data: FAMRecord) => create("/fam/inventory/opening-stock", data),
  inventoryStockMovements: () => list("/fam/inventory/stock-movements"),
  createInventoryStockMovement: (data: FAMRecord) => create("/fam/inventory/stock-movements", data),
  postInventoryStockMovement: (id: number | string, data: FAMRecord) => api.post(`/fam/inventory/stock-movements/${id}/post`, data).then((res) => res.data),
  inventoryStockSummary: () => api.get("/fam/inventory/stock-summary").then((res) => res.data),
  inventoryItemLedger: (id: number | string) => api.get(`/fam/inventory/item-ledger/${id}`).then((res) => res.data),
  createInventoryTransfer: (data: FAMRecord) => create("/fam/inventory/stock-transfers", data),
  postInventoryTransfer: (id: number | string) => api.post(`/fam/inventory/stock-transfers/${id}/post`).then((res) => res.data),
  createInventoryAdjustment: (data: FAMRecord) => create("/fam/inventory/stock-adjustments", data),
  postInventoryAdjustment: (id: number | string, data: FAMRecord) => api.post(`/fam/inventory/stock-adjustments/${id}/post`, data).then((res) => res.data),
  inventoryValuation: () => api.get("/fam/inventory/valuation").then((res) => res.data),
  inventoryReorderAlerts: () => api.get("/fam/inventory/reorder-alerts").then((res) => res.data),
  inventoryReports: () => api.get("/fam/inventory/reports").then((res) => res.data),
  postInventoryCogs: (data: FAMRecord) => create("/fam/inventory/cogs/post", data),
  inventoryAI: (data: FAMRecord) => create("/fam/inventory/ai", data),
  costCenters: () => list("/fam/cost-centers"),
  createCostCenter: (data: FAMRecord) => create("/fam/cost-centers", data),
  branches: () => list("/fam/branches"),
  createBranch: (data: FAMRecord) => create("/fam/branches", data),
  auditLogs: () => list("/fam/audit-logs"),
};
