import React from "react";
import { Navigate } from "react-router-dom";
import type { FrontendRoute } from "@/appRegistry";
import type { FAMViewKind } from "./types";

const FAMWorkspacePage = React.lazy(() => import("./FAMWorkspacePage"));
const ModuleProfilePage = React.lazy(() => import("@/pages/ModuleProfilePage"));

const route = (path: string, kind: FAMViewKind): FrontendRoute => ({
  path,
  element: <FAMWorkspacePage kind={kind} />,
});

const redirect = (path: string, to: string): FrontendRoute => ({
  path,
  element: <Navigate to={to} replace />,
});

export const famRoutes: FrontendRoute[] = [
  route("fam", "dashboard"),
  route("fam/dashboard", "dashboard"),
  { path: "fam/profile", element: <ModuleProfilePage /> },
  route("fam/settings", "settings"),
  route("fam/financial-years", "financialYears"),
  route("fam/chart-of-accounts", "chartOfAccounts"),
  route("fam/ledger-groups", "ledgerGroups"),
  route("fam/ledgers", "ledgers"),
  route("fam/ledgers/:id/entries", "ledgerDetailEntries"),
  route("fam/opening-balances", "openingBalances"),
  route("fam/voucher-types", "voucherTypes"),
  route("fam/vouchers", "vouchers"),
  route("fam/vouchers/new", "voucherNew"),
  route("fam/vouchers/:id", "voucherDetail"),
  route("fam/journal", "journal"),
  route("fam/day-book", "dayBook"),
  route("fam/ledger-entries", "ledgerEntries"),
  route("fam/parties", "parties"),
  route("fam/customers", "customers"),
  route("fam/vendors", "vendors"),
  route("fam/parties/:id", "partyDetail"),
  route("fam/ar", "ar"),
  route("fam/ar/aging", "arAging"),
  route("fam/ar/outstanding", "arOutstanding"),
  route("fam/ap", "ap"),
  route("fam/ap/aging", "apAging"),
  route("fam/ap/outstanding", "apOutstanding"),
  route("fam/bill-references", "billReferences"),
  route("fam/bill-allocations", "billAllocations"),
  route("fam/integrations/srm", "srmIntegration"),
  route("fam/posting-jobs", "postingJobs"),
  route("fam/posting-jobs/:id", "postingJobDetail"),
  route("fam/posting-rules", "postingRules"),
  route("fam/banking", "banking"),
  route("fam/bank-accounts", "bankAccounts"),
  route("fam/payment-modes", "paymentModes"),
  route("fam/bank-statements", "bankStatements"),
  route("fam/bank-statements/:id", "bankStatementDetail"),
  route("fam/bank-reconciliation", "bankReconciliation"),
  route("fam/bank-book", "bankBook"),
  route("fam/cash-book", "cashBook"),
  route("fam/contra", "contra"),
  route("fam/bank-charges", "bankCharges"),
  route("fam/gst", "gst"),
  route("fam/gst/settings", "gstSettings"),
  route("fam/gst/registrations", "gstRegistrations"),
  route("fam/gst/rates", "gstRates"),
  route("fam/gst/hsn-sac", "gstHsnSac"),
  route("fam/gst/sales-register", "gstSalesRegister"),
  route("fam/gst/purchase-register", "gstPurchaseRegister"),
  route("fam/gst/gstr1", "gstr1"),
  route("fam/gst/gstr3b", "gstr3b"),
  route("fam/gst/reconciliation", "gstReconciliation"),
  route("fam/gst/einvoice", "einvoice"),
  route("fam/gst/ewaybill", "ewaybill"),
  route("fam/purchases", "purchases"),
  route("fam/purchase-bills", "purchaseBills"),
  route("fam/purchase-bills/new", "purchaseBillNew"),
  route("fam/purchase-bills/:id", "purchaseBillDetail"),
  route("fam/expenses", "expenses"),
  route("fam/expenses/new", "expenseNew"),
  route("fam/tds", "tds"),
  route("fam/tds/sections", "tdsSections"),
  route("fam/tds/transactions", "tdsTransactions"),
  route("fam/tds/payable", "tdsPayable"),
  route("fam/purchase-register", "purchaseRegister"),
  route("fam/expense-register", "expenseRegister"),
  route("fam/vendor-payments", "vendorPayments"),
  route("fam/payables/dashboard", "payablesDashboard"),
  redirect("fam/inventory", "/srm/inventory"),
  redirect("fam/inventory/accounting", "/srm/inventory/reconciliation"),
  redirect("fam/inventory/dashboard", "/srm/inventory/dashboard"),
  redirect("fam/inventory/items", "/srm/inventory/items"),
  redirect("fam/inventory/items/:id", "/srm/inventory/items"),
  redirect("fam/inventory/items/:id/ledger-mapping", "/srm/inventory/items"),
  redirect("fam/inventory/categories", "/srm/inventory/stock-groups"),
  redirect("fam/inventory/stock-groups", "/srm/inventory/stock-groups"),
  redirect("fam/inventory/units", "/srm/inventory/units"),
  redirect("fam/inventory/warehouses", "/srm/inventory/warehouses"),
  redirect("fam/inventory/stock-in", "/srm/inventory/stock-in"),
  redirect("fam/inventory/stock-out", "/srm/inventory/stock-out"),
  redirect("fam/inventory/stock-transfers", "/srm/inventory/stock-transfers"),
  redirect("fam/inventory/stock-adjustments", "/srm/inventory/stock-adjustments"),
  redirect("fam/inventory/purchase-receipts", "/srm/inventory/purchase-receipts"),
  redirect("fam/inventory/delivery-notes", "/srm/inventory/delivery-notes"),
  redirect("fam/inventory/stock-summary", "/srm/inventory/stock-summary"),
  redirect("fam/inventory/item-ledger/:id", "/srm/inventory/stock-summary"),
  redirect("fam/inventory/warehouse-stock", "/srm/inventory/warehouse-stock"),
  redirect("fam/inventory/stock-aging", "/srm/inventory/stock-aging"),
  redirect("fam/inventory/reorder-report", "/srm/inventory/reorder-report"),
  redirect("fam/inventory/dead-stock", "/srm/inventory/dead-stock"),
  redirect("fam/inventory/fast-slow-moving", "/srm/inventory/fast-slow-moving"),
  redirect("fam/inventory/valuation", "/srm/inventory/valuation"),
  redirect("fam/inventory/gross-margin", "/srm/inventory/gross-margin"),
  redirect("fam/inventory/cogs", "/srm/inventory/cogs"),
  redirect("fam/inventory/grni", "/srm/inventory/reconciliation/grni"),
  redirect("fam/inventory/reconciliation", "/srm/inventory/reconciliation"),
  redirect("fam/inventory/reconciliation/gl", "/srm/inventory/reconciliation/gl"),
  redirect("fam/inventory/reconciliation/grni", "/srm/inventory/reconciliation/grni"),
  redirect("fam/inventory/reconciliation/cogs", "/srm/inventory/reconciliation/cogs"),
  redirect("fam/inventory/reconciliation/gst", "/srm/inventory/reconciliation/gst"),
  redirect("fam/inventory/reports/cogs", "/srm/inventory/reports/cogs"),
  redirect("fam/inventory/reports/gross-margin", "/srm/inventory/reports/gross-margin"),
  redirect("fam/inventory/reports/hsn-summary", "/srm/inventory/reports/hsn-summary"),
  redirect("fam/inventory/audit", "/srm/inventory/audit"),
  redirect("fam/inventory/crm-link", "/srm/inventory/source"),
  redirect("fam/inventory/srm-link", "/srm/inventory/source"),
  redirect("fam/inventory/reorder-alerts", "/srm/inventory/reorder-alerts"),
  redirect("fam/inventory/reports", "/srm/inventory/reports"),
  redirect("fam/inventory/ai", "/srm/inventory/ai"),
  route("fam/cost-centers", "costCenters"),
  route("fam/branches", "branches"),
  route("fam/audit", "audit"),
];
