import React from "react";
import type { FrontendRoute } from "@/appRegistry";
import type { FAMViewKind } from "./types";

const FAMWorkspacePage = React.lazy(() => import("./FAMWorkspacePage"));
const ModuleProfilePage = React.lazy(() => import("@/pages/ModuleProfilePage"));

const route = (path: string, kind: FAMViewKind): FrontendRoute => ({
  path,
  element: <FAMWorkspacePage kind={kind} />,
});

export const famRoutes: FrontendRoute[] = [
  route("fam", "dashboard"),
  route("fam/dashboard", "dashboard"),
  { path: "fam/profile", element: <ModuleProfilePage /> },
  route("fam/settings", "settings"),
  route("fam/financial-years", "financialYears"),
  route("fam/chart-of-accounts", "chartOfAccounts"),
  route("fam/ledger-groups", "ledgerGroups"),
  route("fam/ledgers", "ledgers"),
  route("fam/ledgers/:id/entries", "ledgerDetailEntries"),
  route("fam/opening-balances", "openingBalances"),
  route("fam/voucher-types", "voucherTypes"),
  route("fam/vouchers", "vouchers"),
  route("fam/vouchers/new", "voucherNew"),
  route("fam/vouchers/:id", "voucherDetail"),
  route("fam/journal", "journal"),
  route("fam/day-book", "dayBook"),
  route("fam/ledger-entries", "ledgerEntries"),
  route("fam/parties", "parties"),
  route("fam/customers", "customers"),
  route("fam/vendors", "vendors"),
  route("fam/parties/:id", "partyDetail"),
  route("fam/ar", "ar"),
  route("fam/ar/aging", "arAging"),
  route("fam/ar/outstanding", "arOutstanding"),
  route("fam/ap", "ap"),
  route("fam/ap/aging", "apAging"),
  route("fam/ap/outstanding", "apOutstanding"),
  route("fam/bill-references", "billReferences"),
  route("fam/bill-allocations", "billAllocations"),
  route("fam/integrations/srm", "srmIntegration"),
  route("fam/posting-jobs", "postingJobs"),
  route("fam/posting-jobs/:id", "postingJobDetail"),
  route("fam/posting-rules", "postingRules"),
  route("fam/banking", "banking"),
  route("fam/bank-accounts", "bankAccounts"),
  route("fam/payment-modes", "paymentModes"),
  route("fam/bank-statements", "bankStatements"),
  route("fam/bank-statements/:id", "bankStatementDetail"),
  route("fam/bank-reconciliation", "bankReconciliation"),
  route("fam/bank-book", "bankBook"),
  route("fam/cash-book", "cashBook"),
  route("fam/contra", "contra"),
  route("fam/bank-charges", "bankCharges"),
  route("fam/gst", "gst"),
  route("fam/gst/settings", "gstSettings"),
  route("fam/gst/registrations", "gstRegistrations"),
  route("fam/gst/rates", "gstRates"),
  route("fam/gst/hsn-sac", "gstHsnSac"),
  route("fam/gst/sales-register", "gstSalesRegister"),
  route("fam/gst/purchase-register", "gstPurchaseRegister"),
  route("fam/gst/gstr1", "gstr1"),
  route("fam/gst/gstr3b", "gstr3b"),
  route("fam/gst/reconciliation", "gstReconciliation"),
  route("fam/gst/einvoice", "einvoice"),
  route("fam/gst/ewaybill", "ewaybill"),
  route("fam/purchases", "purchases"),
  route("fam/purchase-bills", "purchaseBills"),
  route("fam/purchase-bills/new", "purchaseBillNew"),
  route("fam/purchase-bills/:id", "purchaseBillDetail"),
  route("fam/expenses", "expenses"),
  route("fam/expenses/new", "expenseNew"),
  route("fam/tds", "tds"),
  route("fam/tds/sections", "tdsSections"),
  route("fam/tds/transactions", "tdsTransactions"),
  route("fam/tds/payable", "tdsPayable"),
  route("fam/purchase-register", "purchaseRegister"),
  route("fam/expense-register", "expenseRegister"),
  route("fam/vendor-payments", "vendorPayments"),
  route("fam/payables/dashboard", "payablesDashboard"),
  route("fam/inventory", "inventory"),
  route("fam/inventory/dashboard", "inventoryDashboard"),
  route("fam/inventory/items", "inventoryItems"),
  route("fam/inventory/items/:id", "inventoryItemDetail"),
  route("fam/inventory/categories", "inventoryCategories"),
  route("fam/inventory/stock-groups", "inventoryStockGroups"),
  route("fam/inventory/units", "inventoryUnits"),
  route("fam/inventory/warehouses", "inventoryWarehouses"),
  route("fam/inventory/stock-in", "inventoryStockIn"),
  route("fam/inventory/stock-out", "inventoryStockOut"),
  route("fam/inventory/stock-transfers", "inventoryStockTransfers"),
  route("fam/inventory/stock-adjustments", "inventoryStockAdjustments"),
  route("fam/inventory/purchase-receipts", "inventoryPurchaseReceipts"),
  route("fam/inventory/delivery-notes", "inventoryDeliveryNotes"),
  route("fam/inventory/stock-summary", "inventoryStockSummary"),
  route("fam/inventory/item-ledger/:id", "inventoryItemLedger"),
  route("fam/inventory/valuation", "inventoryValuation"),
  route("fam/inventory/reorder-alerts", "inventoryReorderAlerts"),
  route("fam/inventory/reports", "inventoryReports"),
  route("fam/inventory/ai", "inventoryAI"),
  route("fam/cost-centers", "costCenters"),
  route("fam/branches", "branches"),
  route("fam/audit", "audit"),
];
